// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btqokydfhdavjiwgydif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0cW9reWRmaGRhdmppd2d5ZGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjU0NTAsImV4cCI6MjA2MzQwMTQ1MH0.GeHg6BUK16BmSB4W5PLVlgHuxaufKCLehpWbMVR-v9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);